# Generated by Django 4.1.4 on 2022-12-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('iccid', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.IntegerField()),
                ('dn', models.IntegerField()),
                ('preactivacion', models.IntegerField(default=0, null=True)),
                ('fecha_activ', models.DateTimeField(blank=True, null=True)),
                ('venta', models.IntegerField(blank=True, null=True)),
                ('idVenta', models.IntegerField(blank=True, null=True)),
                ('fecha_venta', models.DateTimeField(blank=True, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('id_padresucursal', models.IntegerField(blank=True, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id_traslado', models.IntegerField(primary_key=True, serialize=False)),
                ('sucursal_origen', models.IntegerField(blank=True, null=True)),
                ('sucursal_destino', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.marca')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.sucursal')),
            ],
        ),
    ]
